### ISSUE TITLE
How to fix the java.lang.NoSuchMethodError we get when run the project?

### ISSUE THREAD

**Issue by ostapkrutsko** [play-swagger/play-swagger#58]
Hi,

we have a project where play 2.8.8 and Scala 2.13.11 are used.

I and my colleagues are trying to use play-swagger plugin in it. We did all as was written in README in "Get Started" section:

> `Step 1
> For play 2.8, Scala 2.13.x and Scala 2.12.x please use
> 
> addSbtPlugin("io.github.play-swagger" % "sbt-play-swagger" % "1.4.4")`
........

but when we run the project we get the error java.lang.NoSuchMethodError. What can be done to fix this:

`[info] running com.iheart.playSwagger.SwaggerSpecRunner /Users/ostapkrutsko/Projects/exalate-components/jcloudnode/target/swagger/swagger.json routes  com.iheart.playSwagger.ParametricTypeNamesTransformer false 5.7-SNAPSHOT false false none false false
[error] (run-main-0) java.lang.NoSuchMethodError: play.api.libs.json.JsObject$.writes()Lplay/api/libs/json/OWrites;
[error] java.lang.NoSuchMethodError: play.api.libs.json.JsObject$.writes()Lplay/api/libs/json/OWrites;
[error]         at com.iheart.playSwagger.generator.SwaggerSpecGenerator.$anonfun$generate$2(SwaggerSpecGenerator.scala:125)
[error]         at scala.Option.fold(Option.scala:263)
[error]         at com.iheart.playSwagger.generator.SwaggerSpecGenerator.generate(SwaggerSpecGenerator.scala:123)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$.swaggerJson(SwaggerSpecRunner.scala:43)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$.delayedEndpoint$com$iheart$playSwagger$SwaggerSpecRunner$1(SwaggerSpecRunner.scala:49)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$delayedInit$body.apply(SwaggerSpecRunner.scala:10)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:42)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:42)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1(App.scala:98)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:98)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
[error]         at scala.App.main(App.scala:98)
[error]         at scala.App.main$(App.scala:96)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$.main(SwaggerSpecRunner.scala:10)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner.main(SwaggerSpecRunner.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.Run.invokeMain(Run.scala:116)
[error]         at sbt.Run.run0(Run.scala:98)
[error]         at sbt.Run.execute$1(Run.scala:72)
[error]         at sbt.Run.$anonfun$run$4(Run.scala:85)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:257)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at com.iheart.sbtPlaySwagger.SwaggerPlugin$.$anonfun$projectSettings$17(SwaggerPlugin.scala:63)
[error]         at scala.util.Success.foreach(Try.scala:253)
[error]         at com.iheart.sbtPlaySwagger.SwaggerPlugin$.$anonfun$projectSettings$16(SwaggerPlugin.scala:63)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:289)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (swagger) Nonzero exit code: 1
[error] Total time: 14 s, completed Jan 5, 2024 5:10:00 PM
`

**Comment by Javakky-pxv** [comment]
@ostapkrutsko 
Can you provide that project or a reproducible test repository?

**Comment by DrGrognon** [comment]
@Javakky-pxv I got the same issue. This is reproducible directly from the example provided in the lib (delta using last plugin version).
Reproduced here : https://github.com/DrGrognon/play-swagger-example
(I feel this look like a problem with playJson implicit conversion)

**Comment by VikramK** [comment]
Same issue

**Comment by tgodzik** [comment]
@gwak looks like a different issue, do you have a reproduction for that maybe?
