### ISSUE TITLE
Stackoverflow error when trying to generate swagger.json | Spring/Play3/Java21

### ISSUE THREAD

**Issue by julian-perge** [play-swagger/play-swagger#76]
`"io.github.play-swagger" % "sbt-play-swagger" % "2.0.1"`

Unfortunately I can't really give too many details on the models and the project setup due to an NDA.

Had no issues generating before using Java `11`, sbt `1.5.5`, Play `2.8.20`, and `"com.iheart" % "sbt-play-swagger" % "0.10.5-PLAY2.8"` of the plugin (_very old I know_).

Log was truncated since it's just repeating the same stuff over and over.

<details>
<summary>Error</summary>

```
$ sbt swagger --debug --traces --debug-inc --mem 4096

[addSbt] arg = '-debug'
[residual] arg = 'swagger'
[sbt_options] declare -a sbt_options='()'
[process_args] java_version = '21'
[addJava] arg = '-Dsbt.script=/opt/homebrew/Cellar/sbt/1.9.8/libexec/bin/sbt'
[copyRt] java9_rt = '/Users/sweetjp/.sbt/1.0/java9-rt-ext-oracle_corporation_21_0_2/rt.jar'
[addJava] arg = '-Dscala.ext.dirs=/Users/sweetjp/.sbt/1.0/java9-rt-ext-oracle_corporation_21_0_2'
# Executing command line:
java
-Dfile.encoding=UTF-8
-Dsbt.traces=true
-Dxsbt.inc.debug=true
-Xms4096m
-Xmx4096m
-Xss4M
-XX:ReservedCodeCacheSize=512m
-Dsbt.script=/opt/homebrew/Cellar/sbt/1.9.8/libexec/bin/sbt
-Dscala.ext.dirs=/Users/sweetjp/.sbt/1.0/java9-rt-ext-oracle_corporation_21_0_2
-jar
/opt/homebrew/Cellar/sbt/1.9.8/libexec/bin/sbt-launch.jar
-debug
swagger

[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] No changes
...
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 366 products, 197 sources, 22 libraries
...

[info] running com.iheart.playSwagger.SwaggerSpecRunner /Users/sweetjp/test/swagger/swagger.json routes domain.api com.iheart.playSwagger.ParametricTypeNamesTransformer true 1.0.1-dirty-SNAPSHOT true true none true false
[error] java.lang.StackOverflowError
[error]         at scala.reflect.runtime.SynchronizedOps$SynchronizedScope.syncLockSynchronized(SynchronizedOps.scala:59)
[error]         at scala.reflect.runtime.SynchronizedOps$SynchronizedScope.syncLockSynchronized$(SynchronizedOps.scala:59)
[error]         at scala.reflect.runtime.SynchronizedOps$$anon$3.syncLockSynchronized(SynchronizedOps.scala:53)
[error]         at scala.reflect.runtime.SynchronizedOps$SynchronizedScope.lookupEntry(SynchronizedOps.scala:67)
[error]         at scala.reflect.runtime.SynchronizedOps$SynchronizedScope.lookupEntry$(SynchronizedOps.scala:67)
[error]         at scala.reflect.runtime.SynchronizedOps$$anon$3.lookupEntry(SynchronizedOps.scala:53)
...
[error]         at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:171)
[error]         at scala.reflect.internal.Symbols$Symbol.suchThat(Symbols.scala:2045)
[error]         at scala.reflect.internal.Symbols$Symbol.companionClass(Symbols.scala:2360)
[error]         at scala.reflect.internal.Symbols$TermSymbol.companionSymbol(Symbols.scala:2914)
[error]         at scala.reflect.internal.Symbols$SymbolContextApiImpl.companion(Symbols.scala:196)
[error]         at scala.reflect.internal.Symbols$Symbol.symbolKind(Symbols.scala:2698)
[error]         at scala.reflect.internal.Symbols$Symbol.sanitizedKindString(Symbols.scala:2727)
[error]         at scala.reflect.internal.Symbols$Symbol.kindString(Symbols.scala:2735)
[error]         at scala.reflect.internal.Symbols$Symbol.toString(Symbols.scala:2788)
[error]         at java.base/java.lang.String.valueOf(String.java:4465)
[error]         at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
[error]         at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1246)
[error]         at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1241)
[error]         at scala.collection.AbstractIterable.addString(Iterable.scala:933)
[error]         at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1191)
[error]         at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1189)
[error]         at scala.collection.AbstractIterable.mkString(Iterable.scala:933)
[error]         at scala.collection.Iterable.toString(Iterable.scala:78)
[error]         at scala.collection.Iterable.toString$(Iterable.scala:78)
[error]         at scala.collection.Seq.toString(Seq.scala:43)
[error]         at scala.collection.Seq.toString$(Seq.scala:43)
[error]         at scala.collection.AbstractSeq.toString(Seq.scala:1190)
[error]         at java.base/java.lang.String.valueOf(String.java:4465)
[error]         at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:171)
[error]         at scala.reflect.internal.Symbols$Symbol.suchThat(Symbols.scala:2045)
[error]         at scala.reflect.internal.Symbols$ClassSymbol.companionModule0(Symbols.scala:3398)
[error]         at scala.reflect.internal.Symbols$ClassSymbol.companionSymbol(Symbols.scala:3401)
[error]         at scala.reflect.internal.Symbols$SymbolContextApiImpl.companion(Symbols.scala:198)
[error]         at scala.reflect.internal.Symbols$Symbol.symbolKind(Symbols.scala:2698)
[error]         at scala.reflect.internal.Symbols$Symbol.sanitizedKindString(Symbols.scala:2727)
[error]         at scala.reflect.internal.Symbols$Symbol.kindString(Symbols.scala:2735)
[error]         at scala.reflect.internal.Symbols$Symbol.toString(Symbols.scala:2788)
[error]         at scala.reflect.internal.Symbols$ClassSymbol.toString(Symbols.scala:3501)
[error]         at java.base/java.lang.String.valueOf(String.java:4465)
[error]         at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
[error]         at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1246)
[error]         at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1241)
[error]         at scala.collection.AbstractIterable.addString(Iterable.scala:933)
[error]         at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1191)
[error]         at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1189)
[error]         at scala.collection.AbstractIterable.mkString(Iterable.scala:933)
[error]         at scala.collection.Iterable.toString(Iterable.scala:78)
[error]         at scala.collection.Iterable.toString$(Iterable.scala:78)
[error]         at scala.collection.Seq.toString(Seq.scala:43)
[error]         at scala.collection.Seq.toString$(Seq.scala:43)
[error]         at scala.collection.AbstractSeq.toString(Seq.scala:1190)
[error]         at java.base/java.lang.String.valueOf(String.java:4465)
[error]         at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:171)
[error]         at scala.reflect.internal.Symbols$Symbol.suchThat(Symbols.scala:2045)
[error]         at scala.reflect.internal.Symbols$Symbol.companionClass(Symbols.scala:2360)
[error]         at scala.reflect.internal.Symbols$TermSymbol.companionSymbol(Symbols.scala:2914)
[error]         at scala.reflect.internal.Symbols$SymbolContextApiImpl.companion(Symbols.scala:196)
[error]         at scala.reflect.internal.Symbols$Symbol.symbolKind(Symbols.scala:2698)
[error]         at scala.reflect.internal.Symbols$Symbol.sanitizedKindString(Symbols.scala:2727)
[error] (swagger) java.lang.StackOverflowError
[error] Total time: 2 s, completed Feb 22, 2024, 12:03:52 PM
```

</details>

**Comment by julian-perge** [comment]
For further testing, I tried the envOutputTransformer and same result:

```
[info] running com.iheart.playSwagger.SwaggerSpecRunner /Users/sweetjp/test/swagger/swagger.json routes domain.api com.iheart.playSwagger.EnvironmentVariablesTransformer true 1.0.1-dirty-SNAPSHOT true true none true false
[error] java.lang.StackOverflowError
```

**Comment by julian-perge** [comment]
Figured out the problem: nested records.

Having records (or classes) setup like this causes the infinite loop:

```
package mydomain.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.UUID;
import lombok.Builder;

@Builder
public record MyResponse(@JsonProperty(required = true) List<ResponseTwo> responseTwoCollection) {

  @Builder
  public record ResponseTwo(
      @JsonProperty(required = true) UUID id,
      @JsonProperty(required = true) List<MyResponse.ResponseTwo.ResponseThree> responseThreeCollection,
      @JsonProperty(required = true) MyResponse.ResponseTwo.ResponseFour responseFour) {

    @Builder
    public record ResponseThree(@JsonProperty(required = true) String name) {

    }

    @Builder
    public record ResponseFour(
        @JsonProperty(required = true) String param1,
        @JsonProperty(required = true) String param2) {

    }

  }
}
```
